### ISSUE TITLE
Per instance secrets

### ISSUE THREAD

**Issue by sharms** [alphagov/paas-elasticache-broker#6]
Hi!  Your broker looks great, is there any possibility there could be per-instance `seed`?

Reviewing: https://github.com/alphagov/paas-elasticache-broker/blob/bca541acf48bc645a7182ede471585fc75e9a648/redis/provider.go#L245-L248

It looks like the seed is a global (across instances) string which might end up with two possible scenarios:

* Operations team accidentally commits this single secret to a public repo, requiring all instances to be deleted and re-created with a new secret
* Tenant leaks string, and attackers are able to derive the seed because they know the instanceID exposing other tenants

Did you have any thoughts on this?  Would you accept a patch to store a per-instance secret in a database?

**Comment by 46bit** [comment]
Hi @sharms, good question.

> Operations team accidentally commits this single secret to a public repo, requiring all instances to be deleted and re-created with a new secret

That is a real worry. I'll ask the team whether we'd be happy to do that.

> Tenant leaks string, and attackers are able to derive the seed because they know the instanceID exposing other tenants

I had a think about this case and I think we're safe. Let's assume that tenant(s) themselves can be malicious, allowing them to obtain multiple pairs of `instanceID` and `sha256(seed + instanceID)`.

From my understanding, SHA-256 secures against that provided that the `seed` has enough entropy to be hard to brute-force. This is called [pre-image resistance](https://en.wikipedia.org/wiki/Cryptographic_hash_function#Properties). This property of SHA-256 is why Bitcoin mining is so resource-intensive.

We could run a key-derivation algorithm on the seed value provided, to stretch its entropy, but I'm not convinced that has security value because those could be precomputed.

**Comment by 46bit** [comment]
Our systems are quite unlikely to leak the seed, so this isn't a big concern of ours. However it's understandable it would be for other people.

We don't think we would merge a PR that meant we needed to run a database. But it could be an optional feature. We also wouldn't want lots of new dependencies to need to maintain. Frustratingly, I don't think Elasticache is particularly suited for persistently storing secrets, so we probably would need some new libraries.

You could store instance-specific seeds within AWS. They could be added as tags to the instances, and possibly encrypted by the global seed, but that could be a bit unpleasant and backwards incompatible. An optional feature to use AWS Parameter Store could avoid new dependencies while closing this hole for other users. What do you think?

**Comment by jmcarp** [comment]
@46bit: I admire your confidence 😆. Anyway, we have a compliance requirement to rotate credentials periodically (and when we offboard engineers), so even if we were perfectly confident that secrets would never leak, we'd still need to be able to change them. I think we'd be happy to store per-instance credentials in a database or in parameter store.

**Comment by 46bit** [comment]
Us too, I think, at least where possible. Parameter Store seems like the best bet for implementing this, if you'd be open to PRing that?

**Comment by jmcarp** [comment]
@46bit: parameter store would be a good fit, but we aren't able to use it at the moment for compliance reasons (it's not approved through FedRAMP). Any objection to (optionally) storing per-instance credentials in a sql database?

**Comment by jmcarp** [comment]
By the way, we're excited to start using https://github.com/alphagov/paas-rds-broker but will have the same issue to resolve there.

**Comment by 46bit** [comment]
Hey Joshua. Sure thing—provided it’s optional and uses a well-maintained
library I’ll merge using a database for this.

**Comment by 46bit** [comment]
And would for the RDS Broker too.

**Comment by alext** [comment]
> By the way, we're excited to start using https://github.com/alphagov/paas-rds-broker but will have the same issue to resolve there.

I'd note that with the RDS broker it's potentially less of an issue as it supports rotating the master_password_seed - it has a process that runs at startup that checks that it's generated master-password works for each instance, and if not it resets it via the AWS API. This means that to rotate the seed all that needs to be done is to set a new one and restart the broker.

This isn't possible for elasticache because there's currently no option to change the password for an existing instance.

**Comment by samcrang** [comment]
@sharms we've just merged some work we've been doing to move storage over secrets into AWS Security Manager. Hopefully, this should cover your original concerns when raising this issue?

**Comment by jmcarp** [comment]
@samcrang: thanks for the update! Unfortunately, secrets manager isn't available in govcloud and doesn't appear to have fedramp approval (or to be in the fedramp process) in the commercial partition. I'll ask our aws rep about timelines for secrets manager in govcloud, but if we're not able to use it (and I'm guessing we won't), would you be open to a patch supporting another backend?

**Comment by samcrang** [comment]
@jmcarp Ahhh, that's a shame about Secrets Manager. I think we'd be okay with a patch supporting another backend—if it ends up requiring a large amount refactoring to work just give us a heads-up before you spend too long working on it.

**Comment by sharms** [comment]
Hi just to follow up on this, with a sufficient amount of instances, an attacker can derive the original seed.  There is a good thread explaining this for AES: https://x.com/colmmacc/status/1806393666506019256

**Comment by samcrang** [comment]
@sharms 👋🏻

I got notified about your comment because I was involved in this thread previously. Unfortunately I don’t think anyone in this thread still works at GDS so I’m worried that the people who can help you won’t have noticed your comment.

I think your best bet might be to either nudge one of the more recent contributors or perhaps open a new issue so the right people (hopefully!) get visibility of this.
